version: '3.7'

services:
  agile_app_api-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod

    ports:
      - "3001:3001"

    environment:
      - PORT=3001

    volumes:
      - ./src:/usr/src/app/src

  postgres:
    image: bitnami/postgresql:latest
    
    ports:
      - '5432:5432'
      
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_DATABASE}
    
    volumes:
      - pools_pg_data:/bitnami/postgressql
  
    env_file:
      - ".env"

volumes:
  pools_pg_data: