version: '3.8'

services:
  agile_app_api:
    container_name: agile_app_api

    build:
      context: .
      dockerfile: Dockerfile
    
    entrypoint: sh -c 'npm install --frozen-lockfile && npm run start:debug'
    
    depends_on:
      - postgres
    
    env_file:
      - ".env"

    ports:
      - ${PORT}:${PORT}
      - ${PORT_DEBUG}:${PORT_DEBUG}


    environment:
      - PORT=3000
      - NODE_ENV=development

    volumes:
      - ./src:/usr/src/app/src
    
    networks:
      - agile-app-net

  postgres:
    container_name: postgres
    
    image: bitnami/postgresql:latest
    
    ports:
      - '5432:5432'

    env_file:
      - ".env"
      
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_DATABASE}

    volumes:
      - pools_pg_data:/bitnami/postgressql

    networks:
      - agile-app-net
  
volumes:
  pools_pg_data:

networks:
  agile-app-net:
    external: true

