version: '3.7'

services:
  agile_app_api-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod

    ports:
      - "3001:3001"

    environment:
      - PORT=3001

    volumes:
      - ./src:/usr/src/app/src

  postgres:
    image: bitnami/postgresql:latest
    
    ports:
      - '5432:5432'
      
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=pools
    
    volumes:
      - pools_pg_data:/bitnami/postgressql
  

volumes:
  pools_pg_data: